meta:
  engine: 4.2.1

units:
  ky: u
  kx: u

points:
  key:
    padding: ky
    spread: kx

  zones:
    main:
      key:
        tags: [key, switch]
      rows:
        bottom:
          row_net: R2
        home:
          row_net: R1
        top:
          row_net: R0
      columns:
        pinkie:
          key:
            column_net: C0
          rows:
            top:
              key:
                led_prev: LED
                led_next: LED_2
            home:
              key:
                led_prev: LED_10
                led_next: LED_11
            bottom:
              key:
                led_prev: LED_11
                led_next: LED_12

        ring:
          key:
            column_net: C1
            splay: -4
            spread: kx + 2
            stagger: 4
          rows:
            top:
              key:
                led_prev: LED_2
                led_next: LED_3
            home:
              key:
                led_prev: LED_9
                led_next: LED_10
            bottom:
              key:
                led_prev: LED_12
                led_next: LED_13

        middle:
          key:
            column_net: C2
            stagger: 5
          rows:
            top:
              key:
                led_prev: LED_3
                led_next: LED_4
            home:
              key:
                led_prev: LED_8
                led_next: LED_9
            bottom:
              key:
                led_prev: LED_13
                led_next: LED_14

        index:
          key:
            column_net: C3
            stagger: -5
          rows:
            top:
              key:
                led_prev: LED_4
                led_next: LED_5
            home:
              key:
                led_prev: LED_7
                led_next: LED_8
            bottom:
              key:
                led_prev: LED_14
                led_next: LED_15

        far:
          key:
            column_net: C4
            stagger: -5
          rows:
            top:
              key:
                led_prev: LED_5
                led_next: LED_6
            home:
              key:
                led_prev: LED_6
                led_next: LED_7
            bottom:
              key:
                led_prev: LED_15
                led_next: LED_16

    thumb:
      key:
        tags: [key, thumb, switch]
        row_net: R3
      anchor:
        ref: main_far_bottom
        shift: [-5, -20]
      rows:
        thumb:
      columns:
        inner:
          key:
            column_net: C0
            bind: [6, 0, 0, 0]
          rows:
            thumb:
              key:
                led_prev: LED_16
                led_next: LED_17

        home:
          key:
            column_net: C1
            rotate: -30
            shift: [8, -8]
            bind: [7, 5, 0, 12]
          rows:
            thumb:
              key:
                led_prev: LED_17
                led_next: LED_18

        outer:
          key:
            column_net: C2
            rotate: -50
            shift: [10, -25]
            bind: [6, 0, 0, 9]
          rows:
            thumb:
              key:
                led_prev: LED_18
                led_next: LED_OUT

    encoder:
      key:
        tags: [encoder]
      anchor:
        ref: main_far_bottom
        shift: [kx + 8, 0]
      rows:
        enc:
      columns:
        main:

  mirror:
    ref: main_far_home
    distance: 200

outlines:
  main_keys_left:
    - what: rectangle
      where: /^main_.*$/
      asym: source
      size: [kx - 1, ky - 1]
      bound: true

  thumb_keys_left:
    - what: rectangle
      where: /^thumb_.*$/
      asym: source
      size: [kx - 1, ky - 1]
      bound: true

  utility_left:
    - what: rectangle
      asym: source
      where:
        ref: encoder_main_enc
        shift: [-10, 12]
      size: [24, 70]
      fillet: 2

  utility_2_left:
    - what: rectangle
      asym: source
      where:
        ref: main_far_top
        shift: [4.5, 9]
      size: [49, 10]
      fillet: 2

  raw_left:
    - what: outline
      name: main_keys_left
    - what: outline
      name: thumb_keys_left
    - what: outline
      name: utility_left
    - what: outline
      name: utility_2_left

  board_left:
    - what: outline
      name: raw_left
      expand: 3
      fillet: 4

  main_keys_right:
    - what: rectangle
      where: /^main_.*$/
      asym: clone
      size: [kx - 1, ky - 1]
      bound: true

  thumb_keys_right:
    - what: rectangle
      where: /^thumb_.*$/
      asym: clone
      size: [kx - 1, ky - 1]
      bound: true

  utility_right:
    - what: rectangle
      asym: clone
      where:
        ref: encoder_main_enc
        shift: [-10, 12]
      size: [24, 70]
      fillet: 2

  utility_2_right:
    - what: rectangle
      asym: clone
      where:
        ref: main_far_top
        shift: [4.5, 9]
      size: [49, 10]
      fillet: 2

  raw_right:
    - what: outline
      name: main_keys_right
    - what: outline
      name: thumb_keys_right
    - what: outline
      name: utility_right
    - what: outline
      name: utility_2_right

  board_right:
    - what: outline
      name: raw_right
      expand: 3
      fillet: 4

pcbs:
  split36_left:
    template: kicad8

    outlines:
      main:
        outline: board_left

    footprints:
      mx_switches:
        what: ceoloide/switch_mx
        where: /^main_.*$|^thumb_.*$/
        asym: source
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"

      diodes:
        what: ceoloide/diode_tht_sod123
        where: /^main_.*$|^thumb_.*$/
        asym: source
        adjust:
          shift: [0, -7]
          rotate: 180
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"

      encoder:
        what: ceoloide/rotary_encoder_ec11_ec12
        asym: source
        where:
          ref: encoder_main_enc
          shift: [-5, 3]
          rotate: 0

      mcu:
        what: ceoloide/mcu_nice_nano
        asym: source
        where:
          ref: main_far_home
          shift: [20, 20]
          rotate: 0
        params:
          P1: LED
          side: F
          reverse_mount: false
          include_traces: true

      battery_jst:
        what: ceoloide/battery_connector_jst_ph_2
        asym: source
        where:
          ref: main_far_bottom
          shift: [12, 17]
          rotate: 90
        params:
          BAT_P: BAT_P
          BAT_N: GND
          include_courtyard: false

      power_switch:
        what: ceoloide/power_switch_smd_side
        asym: source
        where:
          ref: thumb_home_thumb
          shift: [9, 17]
          rotate: 90
        params:
          from: BAT_P
          to: RAW

      reset_switch:
        what: ceoloide/reset_switch_smd_side
        asym: source
        where:
          ref: main_far_bottom
          shift: [14, -8]
          rotate: 0
        params:
          from: GND
          to: RST
          include_bosses: true

      per_key_leds:
        what: ceoloide/led_sk6812mini-e
        where: /^main_.*$|^thumb_.*$/
        asym: source
        params:
          P1: VCC
          P2: "{{key.led_next}}"
          P3: GND
          P4: "{{key.led_prev}}"
          reverse_mount: true
          include_traces_vias: true
          include_keepout: false
          include_courtyard: false
        adjust:
          shift: [0, -4.5]
          rotate: 0

  split36_right:
    template: kicad8

    outlines:
      main:
        outline: board_right

    footprints:
      mx_switches:
        what: ceoloide/switch_mx
        where: /^main_.*$|^thumb_.*$/
        asym: clone
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"

      diodes:
        what: ceoloide/diode_tht_sod123
        where: /^main_.*$|^thumb_.*$/
        asym: clone
        adjust:
          shift: [0, -7]
          rotate: 180
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"

      encoder:
        what: ceoloide/rotary_encoder_ec11_ec12
        asym: clone
        where:
          ref: encoder_main_enc
          shift: [-5, 3]
          rotate: 0

      mcu:
        what: ceoloide/mcu_nice_nano
        asym: clone
        where:
          ref: main_far_home
          shift: [20, 20]
          rotate: 0
        params:
          P1: LED
          side: F
          reverse_mount: false
          include_traces: true

      battery_jst:
        what: ceoloide/battery_connector_jst_ph_2
        asym: clone
        where:
          ref: main_far_bottom
          shift: [12, 17]
          rotate: 90
        params:
          BAT_P: BAT_P
          BAT_N: GND
          include_courtyard: false

      power_switch:
        what: ceoloide/power_switch_smd_side
        asym: clone
        where:
          ref: thumb_home_thumb
          shift: [9, 17]
          rotate: 90
        params:
          from: BAT_P
          to: RAW

      reset_switch:
        what: ceoloide/reset_switch_smd_side
        asym: clone
        where:
          ref: main_far_bottom
          shift: [14, -8]
          rotate: 0
        params:
          from: GND
          to: RST
          include_bosses: true

      per_key_leds:
        what: ceoloide/led_sk6812mini-e
        where: /^main_.*$|^thumb_.*$/
        asym: clone
        params:
          P1: VCC
          P2: "{{key.led_next}}"
          P3: GND
          P4: "{{key.led_prev}}"
          reverse_mount: true
          include_traces_vias: true
          include_keepout: false
          include_courtyard: false
        adjust:
          shift: [0, -4.5]
          rotate: 0